run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  go: "1.21"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    # Essential linters
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Finds unused code
    
    # Style & formatting
    - gofmt         # Checks if code is formatted
    - goimports     # Checks if imports are formatted
    
    # Code quality
    # - misspell      # Finds commonly misspelled words (disabled)
    - unconvert     # Removes unnecessary type conversions
    # - unparam       # Finds unused function parameters (disabled - too noisy)
    # - dupl          # Finds code duplication (disabled)
    
    # Performance
    - prealloc      # Finds slice declarations with non-zero initial length
    
    # Bugs
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds sending HTTP requests without context
    - rowserrcheck  # Checks Rows.Err is checked
    - sqlclosecheck # Checks SQL rows/statements are closed
    
    # Security
    - gosec         # Security issues

linters-settings:
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/dipsylala/veracodemcp-go
    
  govet:
    enable-all: true
    disable:
      - copylocks
      - fieldalignment
    
  errcheck:
    check-blank: false  # Disabled - allows _ for intentionally ignored errors
    check-type-assertions: false  # Disabled - too noisy for test code
    exclude-functions:
      - (*os.File).Close
      - (io.Closer).Close
      - fmt.Fprintf
      - fmt.Fprintln
      - (*encoding/json.Encoder).Encode
    
  staticcheck:
    checks: ["all"]
    
  unparam:
    check-exported: false  # Don't check exported functions
    
  gosec:
    severity: medium
    confidence: medium
    
  dupl:
    threshold: 100
    
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # Exclude all linters from generated code
  exclude-rules:
    - path: api/generated/
      linters:
        - all
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - errcheck
        - ineffassign
        - govet
      text: "(os.Setenv|os.Unsetenv|os.Chdir|json.Marshal|json.MarshalIndent|tool.Shutdown|type assertion|shadow|G301|G306|ineffectual)"
        
  # Don't hide new issues in existing code
  new: false
